### ISSUE TITLE
Add Indian holidays to the Holidays Calendar

### ISSUE THREAD

**Issue by imkarthikk** [skcript/BlackBook#1]
Add Indian holidays please. I've added just three of them for now. 

@skcript/backend

**Comment by dineshpandianr** [comment]
http://www.officeholidays.com/countries/india/tamil_nadu/2016.php

**Comment by dineshpandianr** [comment]
http://www.officeholidays.com/countries/india/2016.php

**Comment by ashagnanasekar** [comment]
http://www.timebie.com/calendar/india2016.php
